### ISSUE TITLE
x86 DLL and Lib?

### ISSUE THREAD

**Issue by coderkan** [NaJongHeon/QLight-USB-SignalTowerComm#1]
Hi  @NaJongHeon 

Thanks for your simple example about QLight signal tower. I have examined your sample and working on only **x64** architecture. I need **x86** architecture **dll and lib**. **x64** architecture use *Ux64_dllc.dll, Ux64_dllc.lib* dependencies. How can I access if exist **Ux86_dllc.dll and Ux86_dllc.lib**.

Best Regards.
Erkan

**Comment by NaJongHeon** [comment]
Hi @coderkan 

As you said, this works only on x64.

Therefore, you can request x86 API to "QLight" agent of your country.

Thanks

**Comment by coderkan** [comment]
Hi @NaJongHeon 

Thanks for your quick reply.  I have requested from **QLight** agent. I will wait their response. 

Thanks.

**Comment by coderkan** [comment]
Hi,

Thanks for your reply. I have recieved samples and dlls.

Thanks.
Erkan
